name: 'K6 Browser'
description: 'Run K6 Browser tests'
branding:
  icon: 'crosshair'
  color: 'purple'
inputs:
  include:
    description: 'Pattern to match tests'
    required: true
    default: tests/**/*.test.js
  params: 
    description: 'Pass arguments to k6 browser'
  version: 
    description: 'k6 browser version (https://github.com/grafana/xk6-browser)'
    default: v0.10.0
runs:
  using: "composite"
  steps:   
    - uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - uses: actions/cache@v3
      id: cache
      with:
        path: ./k6
        key: ${{ runner.os }}-k6browser-${{ inputs.version }}

    - name: Install k6
      if: steps.cache.outputs.cache-hit != 'true'
      run: go install go.k6.io/xk6/cmd/xk6@latest
      shell: bash

    - name: Build k6
      if: steps.cache.outputs.cache-hit != 'true'
      run: xk6 build --output "k6" --with github.com/grafana/xk6-browser@${{ inputs.version }}
      shell: bash
      
    - name: Install chromium
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: chromium-browser
          version: ${{ inputs.version }}

    - name: Run k6
      run: . ${{ github.action_path }}/script.sh -i ${{ inputs.include }} -p "${{ inputs.params }}"
      shell: bash
